import initAnalytics from "./analytics.js";
import initBanner from "./components/banner.js";
import initBreadcrumb from "./components/breadcrumb.js";
import initClickTheHexagon from "./components/clickTheHexagon.js";
import initConsentBanner from "./components/consentBanner.js";
import initGameOfLife from "./components/gameOfLife.js";
import initRippleText from "./components/rippleText.js";
import initRippleTextOdin from "./components/rippleTextOdin.js";
import initGridBackground from "./components/gridBackground.js";

initAnalytics();
initBanner();
initBreadcrumb();
initClickTheHexagon();
initConsentBanner();
initGameOfLife();
initRippleText();
initRippleTextOdin();
initGridBackground("#main-bg");
initGridBackground("#footer-bg");
